#pragma config(Sensor, dgtl1,  RightDriveEnc,  sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  LeftDriveEnc,   sensorQuadEncoder)
#pragma config(Motor,  port1,           RightFront,    tmotorVex393_HBridge, openLoop, driveRight)
#pragma config(Motor,  port2,           RightRear,     tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port9,           LeftRear,      tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port10,          LeftFront,     tmotorVex393_HBridge, openLoop, reversed, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Global Variables                                                   */
/*   Defined outside of main so they are accessable by the whole program     */
/*---------------------------------------------------------------------------*/
int driverRY = 0; //Right Up/Down channel, driver stick
int driverRX = 0; //Right Left/Right channel, driver stick
int driverLY = 0; //Left Up/Down channel, driver stick
int driverLX = 0; //Left Left/Right channel, driver stick

int RF = 0; //Holds right front wheel value
int RR = 0; //Holds right rear wheel value
int LF = 0; //Holds left front wheel value
int LR = 0; //Holds left rear wheel value

int RDEncoder = 0; //Count of Right Drivetrain encoder
int LDEncoder = 0; //Count of Left Drivetrain encoder


/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	// ..........................................................................
	// Insert user code here.
	// ..........................................................................

	// Remove this function call once you have "real" code.
	AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		// This is the main execution loop for the user control program.
		// Each time through the loop your program should update motor + servo
		// values based on feedback from the joysticks.

		// ........................................................................
		// Insert user code here. This is where you use the joystick values to
		// update your motors, etc.
		// ........................................................................

		// Get joystick values
		driverRY = vexRT[Ch1];
		driverRX = vexRT[Ch2];
		driverLY = vexRT[Ch3];
		driverLX = vexRT[Ch4];

		//Get Encoder values
		RDEncoder = SensorValue[RightDriveEnc];
		LDEncoder = SensorValue[LeftDriveEnc];

		//Perform drive math if necessary

		//Tank Drive
		RF = RR = driverRY;
		LF = LR = driverLY;

		//Arcade
		LF = driverLY + driverLX;
		LR = driverLY + driverLX;
		RF = driverLY - driverLX ;
		RR = driverLY - driverLX ;

		//Tank Holonomic
		LF = driverLY + driverLX;
		LR = driverLY - driverLX;
		RF = driverRY + driverRX ;
		RR = driverRY - driverRX ;

		//Halo Holonomic
		LF = driverLY + driverLX + driverRX;
		LR = driverLY - driverLX + driverRX;
		RF = driverLY - driverLX - driverRX;
		RR = driverLY + driverLX - driverRX;

		//Check if output speeds are in acceptable range
		if(RF>127){RF=127;}
		if(RR>127){RR=127;}
		if(LF>127){LF=127;}
		if(LR>127){LR=127;}
		if(RF<-127){RF=-127;}
		if(RR<-127){RR=-127;}
		if(LF<-127){LF=-127;}
		if(LR<-127){LR=-127;}

		//Assign output values to motors
		motor[RightFront] = RF;
		motor[RightRear] = RR;
		motor[LeftFront] = LF;
		motor[LeftRear] = LR;

	}
}
